# Словарь локализации RU→EN. Ключ — исходная строка интерфейса (русская),
# значение — перевод. Файл самодостаточен: его можно отдавать переводчику.

const EN := {
	# Биомы
	"Изумрудные пещеры": "Emerald Caves",
	"Багровые руины": "Crimson Ruins",
	"Ледяные шахты": "Frozen Mines",
	"Токсичные топи": "Toxic Swamps",
	"Пустынный форт": "Desert Fort",
	"Аметистовая бездна": "Amethyst Abyss",
	"Обсидиановая кузница": "Obsidian Forge",
	# Оружие
	"Пистолет": "Pistol",
	"ПП «Оса»": "SMG \"Wasp\"",
	"Дробовик": "Shotgun",
	"Винтовка": "Rifle",
	"Гранатомёт": "Grenade Launcher",
	"Рельса": "Railgun",
	"Огнемёт": "Flamethrower",
	"Рикошет": "Ricochet",
	"Миниган": "Minigun",
	"Магнум": "Magnum",
	# Улучшения
	"Живучесть": "Vitality",
	"+25 к максимуму здоровья и лечение на 25": "+25 max health and heal 25",
	"Крупный калибр": "Heavy Caliber",
	"+15% к урону всего оружия": "+15% damage to all weapons",
	"Скорострельность": "Rapid Fire",
	"Оружие стреляет на 12% быстрее": "Weapons fire 12% faster",
	"Лёгкие ботинки": "Light Boots",
	"+10% к скорости бега": "+10% run speed",
	"Двойной прыжок": "Double Jump",
	"Дополнительный прыжок в воздухе": "Extra mid-air jump",
	"Вампиризм": "Vampirism",
	"+3 здоровья за каждое убийство": "+3 health per kill",
	"Бронежилет": "Body Armor",
	"Получаемый урон снижен на 15%": "Incoming damage reduced 15%",
	"Крит. патроны": "Crit Rounds",
	"+10% шанс двойного урона": "+10% double-damage chance",
	"Пружины": "Springs",
	"+8% к высоте прыжка": "+8% jump height",
	"Энергощит": "Energy Shield",
	"+30 к запасу щита и медленное восстановление щита": "+30 shield capacity and slow shield regen",
	"Реактивный рывок": "Jet Dash",
	"Перезарядка рывка быстрее на 30%": "Dash cooldown 30% faster",
	"Сапёр": "Sapper",
	"+40% к радиусу и урону ваших взрывов": "+40% radius and damage of your explosions",
	"Магнит": "Magnet",
	"Притягивает монеты и предметы с большего расстояния": "Pulls coins and items from farther away",
	"Берсерк": "Berserker",
	"Чем длиннее серия убийств, тем выше урон": "The longer the kill streak, the higher the damage",
	"Зажигательные": "Incendiary",
	"Пули с шансом поджигают врагов (урон по времени)": "Bullets may ignite enemies (damage over time)",
	"Крио-патроны": "Cryo Rounds",
	"Пули с шансом замораживают врагов (замедление)": "Bullets may freeze enemies (slow)",
	# Реликвии
	"Стеклянная пушка": "Glass Cannon",
	"+60% урона, но −30% к макс. HP": "+60% damage, but −30% max HP",
	"Кровавый клык": "Bloodfang",
	"+10 HP за каждое убийство": "+10 HP per kill",
	"Детонатор": "Detonator",
	"Убитые враги взрываются": "Killed enemies explode",
	"Цепь молний": "Chain Lightning",
	"Попадания бьют током по ближнему врагу": "Hits zap a nearby enemy",
	"Касание Мидаса": "Midas Touch",
	"+1 монета за каждое убийство": "+1 coin per kill",
	"Адреналин": "Adrenaline",
	"При HP < 35%: +40% к скорострельности и бегу": "At HP < 35%: +40% fire rate and run speed",
	"Шипы": "Thorns",
	"Получив урон, ранит окружающих врагов": "When hit, damages surrounding enemies",
	"Второе дыхание": "Second Wind",
	"Раз за уровень переживает смертельный удар (1 HP)": "Once per level, survives a lethal hit (1 HP)",
	"Сверхзаряд": "Overcharge",
	"Ультимейт заряжается на 60% быстрее": "Ultimate charges 60% faster",
	"Морозная аура": "Frost Aura",
	"Близкие враги замедляются": "Nearby enemies are slowed",
	"Регенерация": "Regeneration",
	"Медленно восстанавливает здоровье": "Slowly restores health",
	"Палач": "Executioner",
	"+50% урона по врагам с HP < 30%": "+50% damage to enemies below 30% HP",
	"Бастион": "Bastion",
	"+25 щита в начале каждого уровня": "+25 shield at the start of each level",
	"Охотник": "Hunter",
	"+30% урона по врагам с HP > 70% (первый удар больнее)": "+30% damage to enemies above 70% HP (first hit hurts more)",
	"Сифон": "Siphon",
	"8% нанесённого урона возвращается щитом": "8% of damage dealt returns as shield",
	"Шрапнель": "Shrapnel",
	"Убитый враг выпускает осколки во все стороны": "Slain enemies burst into splinters in all directions",
	"Разгон": "Momentum",
	"Убийство ненадолго ускоряет бег и стрельбу": "A kill briefly boosts run and fire speed",
	"Жажда крови": "Bloodlust",
	"Чем ниже HP, тем выше урон (до +50%)": "The lower your HP, the more damage (up to +50%)",
	"Возмездие": "Vengeance",
	"После получения урона следующее попадание ×2": "After taking damage, your next hit deals ×2",
	# Активные предметы
	"Бомба": "Bomb",
	"Взрыв по области у прицела": "Area blast at the cursor",
	"Блинк": "Blink",
	"Телепорт к прицелу + i-кадры": "Teleport to cursor + i-frames",
	"Заморозка": "Freeze",
	"Замораживает врагов вокруг": "Freezes nearby enemies",
	"Аптечка": "Medkit",
	"Мгновенно +40 HP": "Instantly +40 HP",
	"Щит-нова": "Shield Nova",
	"Щит + отталкивающая волна": "Shield + knockback wave",
	"Турель": "Turret",
	"Ставит авто-турель, что стреляет по врагам": "Deploys an auto-turret that fires at enemies",
	# Классы
	"Солдат": "Soldier",
	"Сбалансирован. Старт: пистолет + ПП «Оса».": "Balanced. Start: pistol + SMG \"Wasp\".",
	"+20% урон, −20% HP. Старт: дробовик + огнемёт.": "+20% damage, −20% HP. Start: shotgun + flamethrower.",
	"Призрак": "Ghost",
	"+30% скорость, двойной прыжок, быстрый рывок, −15% HP. Старт: винтовка.": "+30% speed, double jump, fast dash, −15% HP. Start: rifle.",
	"Инженер": "Engineer",
	"Старт: рикошет + гранатомёт, актив «Щит-нова».": "Start: ricochet + grenade launcher, active \"Shield Nova\".",
	"Танк": "Tank",
	"+60% HP, броня, старт со щитом, −10% скорость.": "+60% HP, armor, start with shield, −10% speed.",
	# Мастерская (мета)
	"Закалка": "Tempering",
	"+20 к стартовому HP за уровень": "+20 starting HP per level",
	"Мощь": "Might",
	"+6% к урону за уровень": "+6% damage per level",
	"Прыть": "Swiftness",
	"+5% к скорости бега за уровень": "+5% run speed per level",
	"Богатство": "Wealth",
	"+5 стартовых монет за уровень": "+5 starting coins per level",
	"Арсенал": "Arsenal",
	"Старт со случайным доп. оружием": "Start with a random extra weapon",
	"Наследие": "Legacy",
	"Старт со случайной реликвией": "Start with a random relic",
	"Скидки": "Discounts",
	"−12% к ценам в магазине за уровень": "−12% shop prices per level",
	# Достижения
	"Первая кровь": "First Blood",
	"Убить первого врага": "Kill your first enemy",
	"Мастер серий": "Streak Master",
	"Серия из 10 убийств": "A streak of 10 kills",
	"Победитель боссов": "Boss Slayer",
	"Одолеть босса": "Defeat a boss",
	"Носить 4 оружия одновременно": "Carry 4 weapons at once",
	"Глубоко": "Deep",
	"Дойти до 10-го уровня": "Reach level 10",
	"Снайпер": "Sniper",
	"Точность 90%+ за забег (30+ выстрелов)": "90%+ accuracy in a run (30+ shots)",
	"Богач": "Rich",
	"Набрать 1000 очков за забег": "Score 1000 points in a run",
	"Живучий": "Survivor",
	"Прожить 3 минуты за один забег": "Survive 3 minutes in a single run",
	"Неудержимый": "Unstoppable",
	"Серия из 25 убийств": "A streak of 25 kills",
	"Магнат": "Tycoon",
	"Набрать 2500 очков за забег": "Score 2500 in a run",
	"Скопидом": "Hoarder",
	"Накопить 60 монет за забег": "Hold 60 coins in a run",
	"Сила реликвий": "Relic Power",
	"Собрать 5 реликвий за один забег": "Collect 5 relics in a single run",
	"Перебор": "Overkill",
	"Нанести 5000 урона за забег": "Deal 5000 damage in a run",
	"Меткий стрелок": "Marksman",
	"Точность 95%+ за забег (50+ выстрелов)": "95%+ accuracy in a run (50+ shots)",
	"Кошмар наяву": "Living Nightmare",
	"Победить босса на «Кошмаре» и выше": "Beat a boss on Nightmare or higher",
	"Двужильный": "Iron-Willed",
	"Прожить 5 минут за один забег": "Survive 5 minutes in a single run",
	"Бездна зовёт": "The Abyss Calls",
	"Дойти до 15-го уровня": "Reach level 15",
	"Сегодня мой день": "My Day Today",
	"Сыграть забег дня": "Play a daily run",
	"1000 убийств за всё время": "1000 kills all-time",
	"Гроза боссов": "Boss Bane",
	"Победить 10 боссов за всё время": "Defeat 10 bosses all-time",
	"Кладоискатель": "Treasure Hunter",
	"Открыть 25 сундуков за всё время": "Open 25 chests all-time",
	"Упорство": "Persistence",
	"Сыграть 25 забегов": "Play 25 runs",
	"Первопроходец": "Trailblazer",
	"Открыть весь контент коллекции": "Unlock all collection content",
	# Сложность
	"Норма": "Normal",
	"Ветеран": "Veteran",
	"Кошмар": "Nightmare",
	"Преисподняя": "Inferno",
	# Боссы
	"СТРАЖ ЗЕМЛИ": "EARTH WARDEN",
	"НЕБЕСНЫЙ СТРАЖ": "SKY WARDEN",
	"КРИСТАЛЬНЫЙ СТРАЖ": "CRYSTAL WARDEN",
	"Обычная": "Common",
	"Редкая": "Rare",
	"Легендарная": "Legendary",
	"Атк": "ATK",
	"Защ": "DEF",
	"Под": "UTL",
	"ПРИЗЫВАТЕЛЬ": "SUMMONER",
	"АРТИЛЛЕРИСТ": "ARTILLERIST",
	"БОСС": "BOSS",
	# Сообщения / HUD / меню
	"Сид дня ": "Daily seed ",
	"Уровень %d — %s": "Level %d — %s",
	"Реликвия: ": "Relic: ",
	"+50 здоровья": "+50 health",
	"Боезапас": "Ammo",
	"Патроны всему оружию": "Ammo for all weapons",
	"Щит": "Shield",
	"+30 к запасу щита": "+30 shield capacity",
	"Оружие": "Weapon",
	"Случайный новый ствол": "A random new gun",
	"Улучшение": "Upgrade",
	"Случайная прокачка": "A random upgrade",
	" (актив, E)": " (active, E)",
	"щит -%d": "shield -%d",
	"Второе дыхание!": "Second Wind!",
	"БОСС ПОВЕРЖЕН! +500": "BOSS DEFEATED! +500",
	"Открыта сложность: ": "Difficulty unlocked: ",
	"Нет патронов!": "Out of ammo!",
	"%s: +патроны": "%s: +ammo",
	"+%d патронов": "+%d ammo",
	"+25 очков": "+25 points",
	"Сначала победите босса!": "Defeat a boss first!",
	"+%d щит": "+%d shield",
	"рывок (Shift/ПКМ)": "dash (Shift/RMB)",
	"ПЕРЕГРУЗКА (Q)": "OVERLOAD (Q)",
	"перегрузка (Q)": "overload (Q)",
	"СЕРИЯ x%d  (очки x%.1f)": "STREAK x%d  (score x%.1f)",
	"Уровень %d · %s": "Level %d · %s",
	"● %d · убийств: %d · сид: %s": "● %d · kills: %d · seed: %s",
	"Доберитесь до портала →": "Reach the portal →",
	"← → / A D — движение": "← → / A D — move",
	"W / Пробел — прыжок": "W / Space — jump",
	"Мышь + ЛКМ — стрельба": "Mouse + LMB — shoot",
	"Shift / ПКМ — рывок": "Shift / RMB — dash",
	"Платформер-рогалик: каждый забег — новая карта": "Platformer roguelike: every run is a new map",
	"Сложность: %s": "Difficulty: %s",
	"(побеждай боссов, чтобы открыть сложнее)": "(beat bosses to unlock higher)",
	"Продолжить": "Continue",
	"Новый забег": "New Run",
	"Играть": "Play",
	"Класс: %s": "Class: %s",
	"Сид дня": "Daily Seed",
	"Управление": "Controls",
	"Достижения  %d/%d": "Achievements  %d/%d",
	"Настройки": "Settings",
	"Мастерская  ◉ %d": "Workshop  ◉ %d",
	"Рекорд: %d очков": "Best: %d points",
	"Удачного первого забега!": "Good luck on your first run!",
	"Enter / клик — старт · ↑↓ — выбор": "Enter / click — start · ↑↓ — select",
	"Классы": "Classes",
	"Ядра: ◉ %d   (клик — выбрать / открыть)": "Cores: ◉ %d   (click — select / unlock)",
	"Выбран": "Selected",
	"Выбрать": "Select",
	"◉ %d — открыть": "◉ %d — unlock",
	"← Назад": "← Back",
	"Бег": "Run",
	"A / D  или  ← / →": "A / D  or  ← / →",
	"Прыжок": "Jump",
	"W / ↑ / Пробел": "W / ↑ / Space",
	"Спрыгнуть с платформы": "Drop through platform",
	"S + прыжок": "S + jump",
	"Прицел / огонь": "Aim / fire",
	"Мышь / ЛКМ": "Mouse / LMB",
	"Рывок (i-кадры)": "Dash (i-frames)",
	"Shift / ПКМ": "Shift / RMB",
	"Ультимейт «Перегрузка»": "Ultimate \"Overload\"",
	"Активный предмет": "Active item",
	"Смена оружия": "Switch weapon",
	"1–8 / колесо мыши": "1–8 / mouse wheel",
	"Громкость": "Volume",
	"Пауза": "Paused",
	"Звук вкл/выкл": "Sound on/off",
	"Полный экран": "Fullscreen",
	"Геймпад: стики — движение/прицел, A — прыжок, RT/RB — огонь, LT/B — рывок, Y — ульта, LB — оружие": "Gamepad: sticks — move/aim, A — jump, RT/RB — fire, LT/B — dash, Y — ult, LB — weapon",
	"Достижения": "Achievements",
	"Открыто %d из %d": "Unlocked %d of %d",
	"В меню": "To Menu",
	"Геймпад поддерживается · F11 — полноэкран": "Gamepad supported · F11 — fullscreen",
	"Громкость (общая)": "Volume (master)",
	"Музыка": "Music",
	"Звуки": "Sound FX",
	"Тряска: %s": "Shake: %s",
	"Вкл": "On",
	"Выкл": "Off",
	"CRT-фильтр: %s": "CRT filter: %s",
	"Экран: %s": "Display: %s",
	"Полный": "Full",
	"Окно": "Window",
	"Окно: %d×%d": "Window: %d×%d",
	"Объёмный свет (рельеф земли): %s": "Volumetric light (ground relief): %s",
	"Вы погибли": "You Died",
	"★ НОВЫЙ РЕКОРД ★": "★ NEW RECORD ★",
	"Очки: %d": "Score: %d",
	"Уровень": "Level",
	"Убийств": "Kills",
	"Лучшая серия": "Best streak",
	"Точность": "Accuracy",
	"Урон нанесён": "Damage dealt",
	"Время": "Time",
	"Рекорд": "Best",
	"Заработано ◉ %d   (всего ◉ %d → Мастерская)": "Earned ◉ %d   (total ◉ %d → Workshop)",
	"Уровень пройден!": "Level cleared!",
	"Выберите улучшение (1 / 2 / 3 или клик):": "Choose an upgrade (1 / 2 / 3 or click):",
	"Магазин": "Shop",
	"Монеты: ● %d   (цифры или клик — купить)": "Coins: ● %d   (number keys or click to buy)",
	"куплено": "bought",
	"Дальше →": "Next →",
	"Мастерская": "Workshop",
	"Ядра: ◉ %d   (клик — купить улучшение)": "Cores: ◉ %d   (click to buy upgrade)",
	"МАКС": "MAX",
	"Достижение: ": "Achievement: ",
	"Язык: %s": "Language: %s",
	"Открыто: ": "Unlocked: ",
	"Коллекция": "Collection",
	"Коллекция  %d/%d": "Collection  %d/%d",
	"Реликвии": "Relics",
	"Открывай оружие и реликвии, играя": "Unlock weapons and relics by playing",
	"убийств": "kills",
	"победить боссов": "defeat bosses",
	"открыть сундуков": "open chests",
	"дойти до уровня": "reach level",
	"завершить забегов": "finish runs",
	"погибнуть раз": "deaths",
	"Кровавый алтарь": "Blood Altar",
	"Отдать 25% макс. HP в обмен на случайную реликвию.": "Sacrifice 25% max HP for a random relic.",
	"Алтарь азарта": "Altar of Chance",
	"Поставить половину монет: с шансом 50% удвоить ставку, иначе потерять.": "Wager half your coins: 50% to double the bet, otherwise lose it.",
	"Алтарь ярости": "Altar of Fury",
	"+25% к урону на весь забег, но пробудить волну врагов.": "+25% damage for the whole run, but awaken a wave of enemies.",
	"Целебный источник": "Healing Spring",
	"Восстановить всё здоровье и щит ценой −10% к максимуму HP.": "Restore all health and shield at the cost of −10% max HP.",
	"Принять": "Accept",
	"Отказаться": "Decline",
	"Решение можно принять только раз": "You can decide only once",
	"Нет монет": "No coins",
	"Выигрыш! +%d●": "Win! +%d●",
	"Проигрыш… −%d●": "Lost… −%d●",
	"Ярость! +25% урона": "Fury! +25% damage",
	"Исцеление!": "Healed!",
	"Алтарь жадности": "Altar of Greed",
	"+1 монета за каждое убийство до конца забега, но получаемый урон +15%.": "+1 coin per kill for the rest of the run, but incoming damage +15%.",
	"Алтарь Хроноса": "Altar of Chronos",
	"Рывок и активный предмет перезаряжаются на 25% быстрее, но −10 макс. HP.": "Dash and active item recharge 25% faster, but −10 max HP.",
	"Жадность!": "Greed!",
	"Ускорение!": "Haste!",
	"Хроно-поле": "Chrono Field",
	"Замедляет время на пару секунд": "Slows down time for a couple of seconds",
	"Удача": "Luck",
	"Враги на 50% чаще роняют лут": "Enemies drop loot 50% more often",
	"Это был мимик!": "It was a mimic!",
}
